package main

import (
	"github.com/abibby/remote-input/common"
	"github.com/abibby/remote-input/windows"
)

var keyMap = map[common.KeyCode]windows.VirtualKey{
	common.KEY_BACKSPACE: windows.VK_BACK,
	common.KEY_ENTER:     windows.VK_RETURN,
	common.KEY_TAB:       windows.VK_TAB,

	common.KEY_CAPSLOCK:   windows.VK_CAPITAL,
	common.KEY_GRAVE:      windows.VK_OEM_3,
	common.KEY_ESC:        windows.VK_ESCAPE,
	common.KEY_SYSRQ:      windows.VK_SNAPSHOT,
	common.KEY_SCROLLLOCK: windows.VK_SCROLL,
	common.KEY_NUMLOCK:    windows.VK_NUMLOCK,
	common.KEY_PAUSE:      windows.VK_PAUSE,
	common.KEY_HOME:       windows.VK_HOME,
	common.KEY_END:        windows.VK_END,
	common.KEY_PAGEUP:     windows.VK_PRIOR,
	common.KEY_PAGEDOWN:   windows.VK_NEXT,
	common.KEY_INSERT:     windows.VK_INSERT,
	common.KEY_KPSLASH:    windows.VK_DIVIDE, // maybePI14

	common.KEY_RIGHTCTRL:  windows.VK_RCONTROL,
	common.KEY_LEFTCTRL:   windows.VK_LCONTROL,
	common.KEY_RIGHTSHIFT: windows.VK_RSHIFT,
	common.KEY_LEFTSHIFT:  windows.VK_LSHIFT,
	common.KEY_RIGHTALT:   windows.VK_RMENU,
	common.KEY_LEFTALT:    windows.VK_LMENU,
	common.KEY_RIGHTMETA:  windows.VK_RWIN,
	common.KEY_LEFTMETA:   windows.VK_LWIN,

	common.KEY_UP:    windows.VK_UP,
	common.KEY_DOWN:  windows.VK_DOWN,
	common.KEY_LEFT:  windows.VK_LEFT,
	common.KEY_RIGHT: windows.VK_RIGHT,

	common.KEY_A:     windows.VK_A,
	common.KEY_B:     windows.VK_B,
	common.KEY_C:     windows.VK_C,
	common.KEY_D:     windows.VK_D,
	common.KEY_E:     windows.VK_E,
	common.KEY_F:     windows.VK_F,
	common.KEY_G:     windows.VK_G,
	common.KEY_H:     windows.VK_H,
	common.KEY_I:     windows.VK_I,
	common.KEY_J:     windows.VK_J,
	common.KEY_K:     windows.VK_K,
	common.KEY_L:     windows.VK_L,
	common.KEY_M:     windows.VK_M,
	common.KEY_N:     windows.VK_N,
	common.KEY_O:     windows.VK_O,
	common.KEY_P:     windows.VK_P,
	common.KEY_Q:     windows.VK_Q,
	common.KEY_R:     windows.VK_R,
	common.KEY_S:     windows.VK_S,
	common.KEY_T:     windows.VK_T,
	common.KEY_U:     windows.VK_U,
	common.KEY_V:     windows.VK_V,
	common.KEY_W:     windows.VK_W,
	common.KEY_X:     windows.VK_X,
	common.KEY_Y:     windows.VK_Y,
	common.KEY_Z:     windows.VK_Z,
	common.KEY_SPACE: windows.VK_SPACE,

	common.KEY_0: windows.VK_0,
	common.KEY_1: windows.VK_1,
	common.KEY_2: windows.VK_2,
	common.KEY_3: windows.VK_3,
	common.KEY_4: windows.VK_4,
	common.KEY_5: windows.VK_5,
	common.KEY_6: windows.VK_6,
	common.KEY_7: windows.VK_7,
	common.KEY_8: windows.VK_8,
	common.KEY_9: windows.VK_9,

	common.KEY_KP0: windows.VK_NUMPAD0,
	common.KEY_KP1: windows.VK_NUMPAD1,
	common.KEY_KP2: windows.VK_NUMPAD2,
	common.KEY_KP3: windows.VK_NUMPAD3,
	common.KEY_KP4: windows.VK_NUMPAD4,
	common.KEY_KP5: windows.VK_NUMPAD5,
	common.KEY_KP6: windows.VK_NUMPAD6,
	common.KEY_KP7: windows.VK_NUMPAD7,
	common.KEY_KP8: windows.VK_NUMPAD8,
	common.KEY_KP9: windows.VK_NUMPAD9,

	common.KEY_F1:  windows.VK_F1,
	common.KEY_F2:  windows.VK_F2,
	common.KEY_F3:  windows.VK_F3,
	common.KEY_F4:  windows.VK_F4,
	common.KEY_F5:  windows.VK_F5,
	common.KEY_F6:  windows.VK_F6,
	common.KEY_F7:  windows.VK_F7,
	common.KEY_F8:  windows.VK_F8,
	common.KEY_F9:  windows.VK_F9,
	common.KEY_F10: windows.VK_F10,
	common.KEY_F11: windows.VK_F11,
	common.KEY_F12: windows.VK_F12,
	common.KEY_F13: windows.VK_F13,
	common.KEY_F14: windows.VK_F14,
	common.KEY_F15: windows.VK_F15,
	common.KEY_F16: windows.VK_F16,
	common.KEY_F17: windows.VK_F17,
	common.KEY_F18: windows.VK_F18,
	common.KEY_F19: windows.VK_F19,
	common.KEY_F20: windows.VK_F20,
	common.KEY_F21: windows.VK_F21,
	common.KEY_F22: windows.VK_F22,
	common.KEY_F23: windows.VK_F23,
	common.KEY_F24: windows.VK_F24,
}
