package common

type InputEventCode = uint16

const (
	KEY_RESERVED   = InputEventCode(0)
	KEY_ESC        = InputEventCode(1)
	KEY_1          = InputEventCode(2)
	KEY_2          = InputEventCode(3)
	KEY_3          = InputEventCode(4)
	KEY_4          = InputEventCode(5)
	KEY_5          = InputEventCode(6)
	KEY_6          = InputEventCode(7)
	KEY_7          = InputEventCode(8)
	KEY_8          = InputEventCode(9)
	KEY_9          = InputEventCode(10)
	KEY_0          = InputEventCode(11)
	KEY_MINUS      = InputEventCode(12)
	KEY_EQUAL      = InputEventCode(13)
	KEY_BACKSPACE  = InputEventCode(14)
	KEY_TAB        = InputEventCode(15)
	KEY_Q          = InputEventCode(16)
	KEY_W          = InputEventCode(17)
	KEY_E          = InputEventCode(18)
	KEY_R          = InputEventCode(19)
	KEY_T          = InputEventCode(20)
	KEY_Y          = InputEventCode(21)
	KEY_U          = InputEventCode(22)
	KEY_I          = InputEventCode(23)
	KEY_O          = InputEventCode(24)
	KEY_P          = InputEventCode(25)
	KEY_LEFTBRACE  = InputEventCode(26)
	KEY_RIGHTBRACE = InputEventCode(27)
	KEY_ENTER      = InputEventCode(28)
	KEY_LEFTCTRL   = InputEventCode(29)
	KEY_A          = InputEventCode(30)
	KEY_S          = InputEventCode(31)
	KEY_D          = InputEventCode(32)
	KEY_F          = InputEventCode(33)
	KEY_G          = InputEventCode(34)
	KEY_H          = InputEventCode(35)
	KEY_J          = InputEventCode(36)
	KEY_K          = InputEventCode(37)
	KEY_L          = InputEventCode(38)
	KEY_SEMICOLON  = InputEventCode(39)
	KEY_APOSTROPHE = InputEventCode(40)
	KEY_GRAVE      = InputEventCode(41)
	KEY_LEFTSHIFT  = InputEventCode(42)
	KEY_BACKSLASH  = InputEventCode(43)
	KEY_Z          = InputEventCode(44)
	KEY_X          = InputEventCode(45)
	KEY_C          = InputEventCode(46)
	KEY_V          = InputEventCode(47)
	KEY_B          = InputEventCode(48)
	KEY_N          = InputEventCode(49)
	KEY_M          = InputEventCode(50)
	KEY_COMMA      = InputEventCode(51)
	KEY_DOT        = InputEventCode(52)
	KEY_SLASH      = InputEventCode(53)
	KEY_RIGHTSHIFT = InputEventCode(54)
	KEY_KPASTERISK = InputEventCode(55)
	KEY_LEFTALT    = InputEventCode(56)
	KEY_SPACE      = InputEventCode(57)
	KEY_CAPSLOCK   = InputEventCode(58)
	KEY_F1         = InputEventCode(59)
	KEY_F2         = InputEventCode(60)
	KEY_F3         = InputEventCode(61)
	KEY_F4         = InputEventCode(62)
	KEY_F5         = InputEventCode(63)
	KEY_F6         = InputEventCode(64)
	KEY_F7         = InputEventCode(65)
	KEY_F8         = InputEventCode(66)
	KEY_F9         = InputEventCode(67)
	KEY_F10        = InputEventCode(68)
	KEY_NUMLOCK    = InputEventCode(69)
	KEY_SCROLLLOCK = InputEventCode(70)
	KEY_KP7        = InputEventCode(71)
	KEY_KP8        = InputEventCode(72)
	KEY_KP9        = InputEventCode(73)
	KEY_KPMINUS    = InputEventCode(74)
	KEY_KP4        = InputEventCode(75)
	KEY_KP5        = InputEventCode(76)
	KEY_KP6        = InputEventCode(77)
	KEY_KPPLUS     = InputEventCode(78)
	KEY_KP1        = InputEventCode(79)
	KEY_KP2        = InputEventCode(80)
	KEY_KP3        = InputEventCode(81)
	KEY_KP0        = InputEventCode(82)
	KEY_KPDOT      = InputEventCode(83)

	KEY_ZENKAKUHANKAKU   = InputEventCode(85)
	KEY_102ND            = InputEventCode(86)
	KEY_F11              = InputEventCode(87)
	KEY_F12              = InputEventCode(88)
	KEY_RO               = InputEventCode(89)
	KEY_KATAKANA         = InputEventCode(90)
	KEY_HIRAGANA         = InputEventCode(91)
	KEY_HENKAN           = InputEventCode(92)
	KEY_KATAKANAHIRAGANA = InputEventCode(93)
	KEY_MUHENKAN         = InputEventCode(94)
	KEY_KPJPCOMMA        = InputEventCode(95)
	KEY_KPENTER          = InputEventCode(96)
	KEY_RIGHTCTRL        = InputEventCode(97)
	KEY_KPSLASH          = InputEventCode(98)
	KEY_SYSRQ            = InputEventCode(99)
	KEY_RIGHTALT         = InputEventCode(100)
	KEY_LINEFEED         = InputEventCode(101)
	KEY_HOME             = InputEventCode(102)
	KEY_UP               = InputEventCode(103)
	KEY_PAGEUP           = InputEventCode(104)
	KEY_LEFT             = InputEventCode(105)
	KEY_RIGHT            = InputEventCode(106)
	KEY_END              = InputEventCode(107)
	KEY_DOWN             = InputEventCode(108)
	KEY_PAGEDOWN         = InputEventCode(109)
	KEY_INSERT           = InputEventCode(110)
	KEY_DELETE           = InputEventCode(111)
	KEY_MACRO            = InputEventCode(112)
	KEY_MUTE             = InputEventCode(113)
	KEY_VOLUMEDOWN       = InputEventCode(114)
	KEY_VOLUMEUP         = InputEventCode(115)
	KEY_POWER            = InputEventCode(116) /* SC System Power Down */
	KEY_KPEQUAL          = InputEventCode(117)
	KEY_KPPLUSMINUS      = InputEventCode(118)
	KEY_PAUSE            = InputEventCode(119)
	KEY_SCALE            = InputEventCode(120) /* AL Compiz Scale (Expose) */

	KEY_KPCOMMA   = InputEventCode(121)
	KEY_HANGEUL   = InputEventCode(122)
	KEY_HANGUEL   = InputEventCode(KEY_HANGEUL)
	KEY_HANJA     = InputEventCode(123)
	KEY_YEN       = InputEventCode(124)
	KEY_LEFTMETA  = InputEventCode(125)
	KEY_RIGHTMETA = InputEventCode(126)
	KEY_COMPOSE   = InputEventCode(127)

	KEY_STOP           = InputEventCode(128) /* AC Stop */
	KEY_AGAIN          = InputEventCode(129)
	KEY_PROPS          = InputEventCode(130) /* AC Properties */
	KEY_UNDO           = InputEventCode(131) /* AC Undo */
	KEY_FRONT          = InputEventCode(132)
	KEY_COPY           = InputEventCode(133) /* AC Copy */
	KEY_OPEN           = InputEventCode(134) /* AC Open */
	KEY_PASTE          = InputEventCode(135) /* AC Paste */
	KEY_FIND           = InputEventCode(136) /* AC Search */
	KEY_CUT            = InputEventCode(137) /* AC Cut */
	KEY_HELP           = InputEventCode(138) /* AL Integrated Help Center */
	KEY_MENU           = InputEventCode(139) /* Menu (show menu) */
	KEY_CALC           = InputEventCode(140) /* AL Calculator */
	KEY_SETUP          = InputEventCode(141)
	KEY_SLEEP          = InputEventCode(142) /* SC System Sleep */
	KEY_WAKEUP         = InputEventCode(143) /* System Wake Up */
	KEY_FILE           = InputEventCode(144) /* AL Local Machine Browser */
	KEY_SENDFILE       = InputEventCode(145)
	KEY_DELETEFILE     = InputEventCode(146)
	KEY_XFER           = InputEventCode(147)
	KEY_PROG1          = InputEventCode(148)
	KEY_PROG2          = InputEventCode(149)
	KEY_WWW            = InputEventCode(150) /* AL Internet Browser */
	KEY_MSDOS          = InputEventCode(151)
	KEY_COFFEE         = InputEventCode(152) /* AL Terminal Lock/Screensaver */
	KEY_SCREENLOCK     = InputEventCode(KEY_COFFEE)
	KEY_ROTATE_DISPLAY = InputEventCode(153) /* Display orientation for e.g. tablets */
	KEY_DIRECTION      = InputEventCode(KEY_ROTATE_DISPLAY)
	KEY_CYCLEWINDOWS   = InputEventCode(154)
	KEY_MAIL           = InputEventCode(155)
	KEY_BOOKMARKS      = InputEventCode(156) /* AC Bookmarks */
	KEY_COMPUTER       = InputEventCode(157)
	KEY_BACK           = InputEventCode(158) /* AC Back */
	KEY_FORWARD        = InputEventCode(159) /* AC Forward */
	KEY_CLOSECD        = InputEventCode(160)
	KEY_EJECTCD        = InputEventCode(161)
	KEY_EJECTCLOSECD   = InputEventCode(162)
	KEY_NEXTSONG       = InputEventCode(163)
	KEY_PLAYPAUSE      = InputEventCode(164)
	KEY_PREVIOUSSONG   = InputEventCode(165)
	KEY_STOPCD         = InputEventCode(166)
	KEY_RECORD         = InputEventCode(167)
	KEY_REWIND         = InputEventCode(168)
	KEY_PHONE          = InputEventCode(169) /* Media Select Telephone */
	KEY_ISO            = InputEventCode(170)
	KEY_CONFIG         = InputEventCode(171) /* AL Consumer Control Configuration */
	KEY_HOMEPAGE       = InputEventCode(172) /* AC Home */
	KEY_REFRESH        = InputEventCode(173) /* AC Refresh */
	KEY_EXIT           = InputEventCode(174) /* AC Exit */
	KEY_MOVE           = InputEventCode(175)
	KEY_EDIT           = InputEventCode(176)
	KEY_SCROLLUP       = InputEventCode(177)
	KEY_SCROLLDOWN     = InputEventCode(178)
	KEY_KPLEFTPAREN    = InputEventCode(179)
	KEY_KPRIGHTPAREN   = InputEventCode(180)
	KEY_NEW            = InputEventCode(181) /* AC New */
	KEY_REDO           = InputEventCode(182) /* AC Redo/Repeat */

	KEY_F13 = InputEventCode(183)
	KEY_F14 = InputEventCode(184)
	KEY_F15 = InputEventCode(185)
	KEY_F16 = InputEventCode(186)
	KEY_F17 = InputEventCode(187)
	KEY_F18 = InputEventCode(188)
	KEY_F19 = InputEventCode(189)
	KEY_F20 = InputEventCode(190)
	KEY_F21 = InputEventCode(191)
	KEY_F22 = InputEventCode(192)
	KEY_F23 = InputEventCode(193)
	KEY_F24 = InputEventCode(194)

	KEY_PLAYCD           = InputEventCode(200)
	KEY_PAUSECD          = InputEventCode(201)
	KEY_PROG3            = InputEventCode(202)
	KEY_PROG4            = InputEventCode(203)
	KEY_ALL_APPLICATIONS = InputEventCode(204) /* AC Desktop Show All Applications */
	KEY_DASHBOARD        = InputEventCode(KEY_ALL_APPLICATIONS)
	KEY_SUSPEND          = InputEventCode(205)
	KEY_CLOSE            = InputEventCode(206) /* AC Close */
	KEY_PLAY             = InputEventCode(207)
	KEY_FASTFORWARD      = InputEventCode(208)
	KEY_BASSBOOST        = InputEventCode(209)
	KEY_PRINT            = InputEventCode(210) /* AC Print */
	KEY_HP               = InputEventCode(211)
	KEY_CAMERA           = InputEventCode(212)
	KEY_SOUND            = InputEventCode(213)
	KEY_QUESTION         = InputEventCode(214)
	KEY_EMAIL            = InputEventCode(215)
	KEY_CHAT             = InputEventCode(216)
	KEY_SEARCH           = InputEventCode(217)
	KEY_CONNECT          = InputEventCode(218)
	KEY_FINANCE          = InputEventCode(219) /* AL Checkbook/Finance */
	KEY_SPORT            = InputEventCode(220)
	KEY_SHOP             = InputEventCode(221)
	KEY_ALTERASE         = InputEventCode(222)
	KEY_CANCEL           = InputEventCode(223) /* AC Cancel */
	KEY_BRIGHTNESSDOWN   = InputEventCode(224)
	KEY_BRIGHTNESSUP     = InputEventCode(225)
	KEY_MEDIA            = InputEventCode(226)

	KEY_SWITCHVIDEOMODE = InputEventCode(227) /* Cycle between available video
	   outputs (Monitor/LCD/TV-out/etc) */
	KEY_KBDILLUMTOGGLE = InputEventCode(228)
	KEY_KBDILLUMDOWN   = InputEventCode(229)
	KEY_KBDILLUMUP     = InputEventCode(230)

	KEY_SEND        = InputEventCode(231) /* AC Send */
	KEY_REPLY       = InputEventCode(232) /* AC Reply */
	KEY_FORWARDMAIL = InputEventCode(233) /* AC Forward Msg */
	KEY_SAVE        = InputEventCode(234) /* AC Save */
	KEY_DOCUMENTS   = InputEventCode(235)

	KEY_BATTERY = InputEventCode(236)

	KEY_BLUETOOTH = InputEventCode(237)
	KEY_WLAN      = InputEventCode(238)
	KEY_UWB       = InputEventCode(239)

	KEY_UNKNOWN = InputEventCode(240)

	KEY_VIDEO_NEXT       = InputEventCode(241) /* drive next video source */
	KEY_VIDEO_PREV       = InputEventCode(242) /* drive previous video source */
	KEY_BRIGHTNESS_CYCLE = InputEventCode(243) /* brightness up, after max is min */
	KEY_BRIGHTNESS_AUTO  = InputEventCode(244) /* Set Auto Brightness: manual
	brightness control is off,
	rely on ambient */
	KEY_BRIGHTNESS_ZERO = InputEventCode(KEY_BRIGHTNESS_AUTO)
	KEY_DISPLAY_OFF     = InputEventCode(245) /* display device to off state */

	KEY_WWAN   = InputEventCode(246) /* Wireless WAN (LTE, UMTS, GSM, etc.) */
	KEY_WIMAX  = InputEventCode(KEY_WWAN)
	KEY_RFKILL = InputEventCode(247) /* Key that controls all radios */

	KEY_MICMUTE = InputEventCode(248) /* Mute / unmute the microphone */

	MOUSE_LEFT    = InputEventCode(272)
	MOUSE_RIGHT   = InputEventCode(273)
	MOUSE_MIDDLE  = InputEventCode(274)
	MOUSE_BACK    = InputEventCode(275)
	MOUSE_FORWARD = InputEventCode(276)

	JOYSTICK_BASE = InputEventCode(304) //0x130
)
